name: NodeJS with Webpack

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Copy index.html to 404.html in Checks
        run: cp dist/dasboard-entradas-salidas/checks/index.html dist/dasboard-entradas-salidas/checks/404.html

      - name: Copy index.html to 404.html
        run: cp dist/dasboard-entradas-salidas//browser/index.html dist/dasboard-entradas-salidas/browser/404.html

      - name: List files for debugging
        run: ls -R dist/dasboard-entradas-salidas/browser

      - name: Deploy GitHub Pages site
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          build_dir: ./dist/dasboard-entradas-salidas
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
