name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.4.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build:prod

    - name: Copy index.html to 404.html in Checks
      run: cp dist/dasboard-entradas-salidas/checks/index.html dist/dasboard-entradas-salidas/checks/404.html

    - name: Copy index.html to 404.html
      run: cp dist/dasboard-entradas-salidas//browser/index.html dist/dasboard-entradas-salidas/browser/404.html

    - name: List files for debugging
      run: ls -R dist/dasboard-entradas-salidas/browser

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
      with: 
        publish_dir: ./dist/dasboard-entradas-salidas
      
